(function(){
  const BASE=location.pathname.startsWith('/ui')?'/ui':'';const api=p=>BASE+p;const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let tasks=[],inbox=[],overview={},knowledge={},activeTask=null;
  async function get(path){const r=await fetch(api(path),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
  function nav(){document.querySelectorAll('[data-panel]').forEach(a=>a.onclick=e=>{e.preventDefault();show(a.dataset.panel)});document.querySelectorAll('[data-action="new-task"]').forEach(b=>b.onclick=()=>$('#task-dialog').showModal());}
  function show(name){document.querySelectorAll('[data-panel-content]').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===name));const navName=['services','knowledge'].includes(name)?'more':name;document.querySelectorAll('.cc-nav').forEach(a=>a.classList.toggle('active',a.dataset.panel===navName));$('#page-title').textContent={home:'مركز القيادة',tasks:'المهام',inbox:'صندوق الوارد',chat:'المحادثة',more:'المزيد',knowledge:'المعرفة',services:'الخدمات'}[name]||'مركز القيادة';location.hash=name;if(name==='tasks')renderTasks();if(name==='inbox')renderInbox();if(name==='services')renderServices();if(name==='knowledge')renderKnowledge();}
  function metric(label,value,note,target){return `<button class="cc-metric" data-panel="${esc(target||'tasks')}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></button>`}
  const statusLabels={received:'مستلمة',planning:'تخطيط',delegated:'مفوّضة',running:'قيد التنفيذ',completed:'مكتملة',failed:'فاشلة',cancelled:'ملغاة'};
  function renderHome(){const failed=tasks.filter(t=>t.status==='failed').length,running=tasks.filter(t=>['received','planning','delegated','running'].includes(t.status)).length,done=tasks.filter(t=>t.status==='completed').length;$('#home-metrics').innerHTML=metric('قيد التنفيذ',running,'من /api/tasks','tasks')+metric('فشل التنفيذ',failed,'بيانات حقيقية','tasks')+metric('مكتملة',done,'منذ بدء التخزين','tasks')+metric('النتائج',inbox.length,'من /api/inbox','inbox');$('#home-tasks').innerHTML=tasks.slice(0,3).map(taskCard).join('')||empty('لا توجد مهام بعد');$('#home-inbox').innerHTML=inbox.slice(0,3).map(artifactCard).join('')||empty('لا توجد نتائج بعد');const events=[];tasks.forEach(t=>{if(t._events)events.push(...t._events)});$('#home-events').innerHTML=events.sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,3).map(eventRow).join('')||empty('لا توجد أحداث بعد');}
  function taskCard(t){return `<button class="cc-task" data-task="${esc(t.id)}"><span class="cc-status ${esc(t.status)}"></span><div><b>${esc(t.title||'مهمة بلا عنوان')}</b><small class="ltr">${esc(t.id)}</small></div><em>${esc(statusLabels[t.status]||'UNAVAILABLE')}</em></button>`}
  function artifactCard(a){return `<button class="cc-artifact" data-artifact="${esc(a.artifact_id||a.id)}"><span class="cc-file">▤</span><div><b>${esc(a.title||'بدون عنوان')}</b><small>${esc(a.source_type||'UNAVAILABLE')} · ${esc(a.created_at||'')}</small></div><em>${esc(a.health_state||'UNAVAILABLE')}</em></button>`}
  function eventRow(e){const labels={'task.received':'تم استلام المهمة','task.planning':'جارٍ تجهيز المهمة','run.started':'بدأ التنفيذ','hermes.response':'وصل رد Hermes','artifact.created':'تم حفظ النتيجة','run.completed':'اكتمل التنفيذ','run.failed':'فشل التنفيذ'};return `<button type="button" class="cc-event" data-run="${esc(e.run_id||'')}" title="فتح سجل التنفيذ"><span class="cc-event-dot ${esc(e.status)}"></span><div><b>${esc(labels[e.event_type]||'حدث غير معروف')}</b><small>${esc(e.message||'')} · <span class="ltr">${esc((e.run_id||'').slice(0,18))}</span></small></div><time class="ltr">${esc(e.timestamp||'')}</time></button>`}
  function empty(t){return `<div class="cc-empty">${esc(t)}</div>`}
  function renderTasks(){const q=($('#tasks-search')?.value||'').toLowerCase(),status=$('#tasks-status')?.value||'',sort=$('#tasks-sort')?.value||'updated';const rows=tasks.filter(t=>(!status||t.status===status)&&`${t.title} ${t.prompt} ${t.id}`.toLowerCase().includes(q)).sort((a,b)=>sort==='title'?String(a.title).localeCompare(String(b.title),'ar'):String(b[sort==='created'?'created_at':'updated_at']||b.created_at).localeCompare(String(a[sort==='created'?'created_at':'updated_at']||a.created_at)));$('#tasks-list').innerHTML=rows.map(taskCard).join('')||empty('لا توجد مهام مطابقة.');}
  function renderInbox(){const q=($('#inbox-search')?.value||'').toLowerCase(),type=$('#inbox-type')?.value||'';$('#inbox-list').innerHTML=inbox.filter(a=>(!type||a.mime_type===type||a.type===type)&&`${a.title} ${a.content} ${a.source_type}`.toLowerCase().includes(q)).map(artifactCard).join('')||empty('لا توجد نتائج مطابقة.');}
  function renderServices(){const sources=overview.sources||{};$('#services-list').innerHTML=Object.entries(sources).map(([name,s])=>`<article class="cc-service"><span class="cc-status ${s.health_state==='available'||s.health_state==='configured'?'completed':'unavailable'}"></span><h3>${esc(name)}</h3><b>${esc(s.health_state||'UNAVAILABLE')}</b><small>${esc(s.data_origin||'UNAVAILABLE')}<br>${esc(s.source_id||'UNAVAILABLE')}</small></article>`).join('')||empty('لا توجد خدمات موثقة.');}
  function renderKnowledge(){const s=overview.sources?.knowledge_graph||{};const status=knowledge.status||s.health_state||'UNAVAILABLE';const count=Array.isArray(knowledge.nodes)?knowledge.nodes.length:0;$('#knowledge-state').innerHTML=`<span class="cc-knowledge-icon">⌘</span><h3>${status==='UNAVAILABLE'?'لا توجد ملاحظات متاحة بعد':'المعرفة المترابطة'}</h3><p>المصدر: <span class="ltr">${esc(knowledge.source_id||s.source_id||'UNAVAILABLE')}</span><br>عدد العقد: <b>${esc(count)}</b><br>Graph: <b>${esc(status)}</b></p><small>${esc(knowledge.reason||'تُعرض العلاقات من المصدر الفعلي فقط، دون بيانات تجريبية.')}</small>`;}
  function loading(el){if(el)el.innerHTML='<div class="cc-loading" role="status">جارٍ تحميل البيانات...</div>';}
  async function watchTask(id){for(let attempt=0;attempt<40;attempt++){try{const d=await get('/api/tasks/'+id);const row=tasks.find(t=>t.id===id);if(row){Object.assign(row,d.task);row._events=d.events||[];renderHome();renderTasks()}if(['completed','failed','cancelled'].includes(d.task?.status)){await load();return d.task.status}}catch{}await new Promise(resolve=>setTimeout(resolve,750))}return 'timeout'}
  async function load(){loading($('#home-events'));loading($('#tasks-list'));loading($('#inbox-list'));try{[overview,knowledge]=await Promise.all([get('/api/system/overview'),get('/api/knowledge/graph')]);const ti=await get('/api/tasks');tasks=ti.tasks||[];for(const t of tasks){try{const d=await get('/api/tasks/'+t.id);t._events=d.events||[]}catch{t._events=[]}}const ii=await get('/api/inbox?limit=100');inbox=ii.items||[];$('#global-health').textContent=overview.health_state||'UNAVAILABLE';renderHome();renderTasks();renderInbox();renderServices();renderKnowledge();}catch(e){$('#global-health').textContent='UNAVAILABLE';const message='تعذر تحميل المصادر. حاول التحديث.';$('#home-events').innerHTML=`<div class="cc-error" role="alert">${esc(message)} <button class="cc-secondary" data-action="refresh">إعادة المحاولة</button></div>`;$('#tasks-list').innerHTML=empty(message);$('#inbox-list').innerHTML=empty(message)}}
  async function openRun(id){if(!id)return;try{const d=await get('/api/runs/'+id);$('#detail-content').innerHTML=`<span class="eyebrow">RUN DETAILS</span><h2>سجل التنفيذ</h2><div class="cc-detail-meta"><b>run_id</b><span class="ltr">${esc(d.run?.id||id)}</span><b>status</b><span>${esc(statusLabels[d.run?.status]||d.run?.status||'UNAVAILABLE')}</span><b>profile</b><span>${esc(d.run?.profile||'UNAVAILABLE')}</span><b>started</b><span class="ltr">${esc(d.run?.started_at||'UNAVAILABLE')}</span><b>completed</b><span class="ltr">${esc(d.run?.completed_at||'UNAVAILABLE')}</span></div><div class="cc-events">${(d.events||[]).map(eventRow).join('')||empty('لا توجد أحداث لهذا التنفيذ.')}</div>`;$('#detail-dialog').showModal()}catch(e){alert('تعذر فتح سجل التنفيذ')}}
  async function openTask(id){try{const d=await get('/api/tasks/'+id);activeTask=d;$('#detail-content').innerHTML=`<span class="eyebrow">TASK DETAILS</span><h2>${esc(d.task.title)}</h2><p>${esc(d.task.prompt)}</p><div class="cc-detail-meta"><b>الحالة</b><span>${esc(statusLabels[d.task.status]||'UNAVAILABLE')}</span><b>task_id</b><span class="ltr">${esc(d.task.id)}</span><b>run_id</b><button type="button" class="cc-link ltr" data-run="${esc(d.run?.id||'')}">${esc(d.run?.id||'UNAVAILABLE')}</button><b>conversation</b><span class="ltr">${esc(d.task.conversation_id||'UNAVAILABLE')}</span></div><div class="cc-events">${(d.events||[]).map(eventRow).join('')||empty('لا توجد أحداث بعد.')}</div>${d.task.artifact_id?`<button type="button" class="cc-primary" data-artifact="${esc(d.task.artifact_id)}">فتح النتيجة</button>`:''}${d.task.status==='failed'?`<button type="button" class="cc-secondary" data-retry="${esc(d.task.id)}">إعادة المحاولة</button>`:''}`;$('#detail-dialog').showModal()}catch(e){alert('تعذر فتح المهمة')}}
  async function openArtifact(id){try{const a=await get('/api/artifacts/'+id);$('#detail-content').innerHTML=`<span class="eyebrow">ARTIFACT</span><h2>${esc(a.title)}</h2><div class="cc-detail-actions"><button type="button" class="cc-secondary" data-copy="${esc(a.id)}">نسخ</button><button type="button" class="cc-secondary" data-download="${esc(a.id)}">تنزيل</button></div><div class="cc-detail-meta"><b>task_id</b><span class="ltr">${esc(a.task_id||'UNAVAILABLE')}</span><b>run_id</b><button type="button" class="cc-link ltr" data-run="${esc(a.run_id||'')}">${esc(a.run_id||'UNAVAILABLE')}</button><b>mime</b><span>${esc(a.mime_type||'UNAVAILABLE')}</span><b>source</b><span>${esc(a.source_type||'UNAVAILABLE')} / ${esc(a.source_id||'UNAVAILABLE')}</span><b>origin</b><span>${esc(a.data_origin||'UNAVAILABLE')}</span><b>verified</b><span class="ltr">${esc(a.last_verified_at||'UNAVAILABLE')}</span></div><pre id="artifact-content" class="cc-content">${esc(a.content||a.summary||'UNAVAILABLE')}</pre>`;$('#detail-dialog').dataset.artifact=JSON.stringify({id:a.id,title:a.title,content:a.content||a.summary||''});$('#detail-dialog').showModal()}catch(e){alert('تعذر فتح النتيجة')}}
  async function createTask(e){e.preventDefault();const button=$('#task-form button[type="submit"]');button.disabled=true;try{const p={title:$('#task-title').value,prompt:$('#task-prompt').value};const r=await fetch(api('/api/tasks'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر إنشاء المهمة');$('#task-dialog').close();await load();show('tasks');if(d.task?.id){openTask(d.task.id);watchTask(d.task.id)}}finally{button.disabled=false}}
  async function chat(){const input=$('#chat-input'),text=input.value.trim();if(!text)return;const button=$('#chat-send');button.disabled=true;$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg user">${esc(text)}</div>`);input.value='';$('#chat-state').textContent='جارٍ الاتصال بـHermes...';try{const r=await fetch(api('/api/chat'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const d=await r.json();if(!r.ok)throw Error(d.error||'تعذر الاتصال');$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg">${esc(d.reply||'UNAVAILABLE')}</div>`);$('#chat-state').textContent='متصل'}catch(e){$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-error" role="alert">${esc(e.message)} <button class="cc-secondary" data-chat-retry="${esc(text)}">إعادة المحاولة</button></div>`);$('#chat-state').textContent='تعذر الاتصال'}finally{button.disabled=false;$('#chat-thread').scrollTop=$('#chat-thread').scrollHeight}}
  document.addEventListener('click',e=>{const panel=e.target.closest('[data-panel]');if(panel){e.preventDefault();show(panel.dataset.panel);return}const t=e.target.closest('[data-task]');if(t)openTask(t.dataset.task);const a=e.target.closest('[data-artifact]');if(a)openArtifact(a.dataset.artifact);const run=e.target.closest('[data-run]');if(run)openRun(run.dataset.run);const r=e.target.closest('[data-retry]');if(r)fetch(api('/api/tasks/'+r.dataset.retry+'/retry'),{method:'POST'}).then(()=>load());const copy=e.target.closest('[data-copy]');if(copy){const data=JSON.parse($('#detail-dialog').dataset.artifact||'{}');Promise.resolve(navigator.clipboard?.writeText(data.content||'')).then(()=>{copy.textContent='تم النسخ'});};const download=e.target.closest('[data-download]');if(download){const data=JSON.parse($('#detail-dialog').dataset.artifact||'{}'),url=URL.createObjectURL(new Blob([data.content||''],{type:'text/markdown'})),link=document.createElement('a');link.href=url;link.download=(data.title||'artifact')+'.md';link.click();URL.revokeObjectURL(url)}const retryChat=e.target.closest('[data-chat-retry]');if(retryChat){$('#chat-input').value=retryChat.dataset.chatRetry;chat()}const refresh=e.target.closest('[data-action="refresh"]');if(refresh)load();});$('#task-form').addEventListener('submit',e=>createTask(e).catch(err=>alert(err.message)));$('#chat-send').onclick=()=>chat();$('#inbox-search').oninput=renderInbox;$('#inbox-type').onchange=renderInbox;$('#tasks-search').oninput=renderTasks;$('#tasks-status').onchange=renderTasks;$('#tasks-sort').onchange=renderTasks;nav();load();show(location.hash.slice(1)||'home');
})();
