(function(){
  const BASE=location.pathname.startsWith('/ui')?'/ui':'';const api=p=>BASE+p;const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let tasks=[],inbox=[],overview={},activeTask=null;
  async function get(path){const r=await fetch(api(path),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
  function nav(){document.querySelectorAll('[data-panel]').forEach(a=>a.onclick=e=>{e.preventDefault();show(a.dataset.panel)});document.querySelectorAll('[data-action="new-task"]').forEach(b=>b.onclick=()=>$('#task-dialog').showModal());}
  function show(name){document.querySelectorAll('[data-panel-content]').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===name));document.querySelectorAll('.cc-nav').forEach(a=>a.classList.toggle('active',a.dataset.panel===name));$('#page-title').textContent={home:'مركز القيادة',tasks:'المهام',inbox:'صندوق الوارد',chat:'المحادثة',knowledge:'المعرفة',services:'الخدمات'}[name]||'مركز القيادة';location.hash=name;if(name==='tasks')renderTasks();if(name==='inbox')renderInbox();if(name==='services')renderServices();if(name==='knowledge')renderKnowledge();}
  function metric(label,value,note){return `<div class="cc-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
  function renderHome(){const failed=tasks.filter(t=>t.status==='failed').length,running=tasks.filter(t=>t.status==='running').length,done=tasks.filter(t=>t.status==='completed').length;$('#home-metrics').innerHTML=metric('مهام نشطة',running,'من /api/tasks')+metric('فشل التنفيذ',failed,'بيانات حقيقية')+metric('مكتملة',done,'منذ بدء التخزين')+metric('مصدر البيانات',overview.data_origin||'UNAVAILABLE','آخر تحقق '+(overview.last_verified_at||'UNAVAILABLE'));$('#home-tasks').innerHTML=tasks.slice(0,5).map(taskCard).join('')||empty('لا توجد مهام بعد');$('#home-inbox').innerHTML=inbox.slice(0,5).map(artifactCard).join('')||empty('لا توجد نتائج بعد');const events=[];tasks.forEach(t=>{if(t._events)events.push(...t._events)});$('#home-events').innerHTML=events.sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,8).map(eventRow).join('')||empty('لا توجد أحداث بعد');}
  function taskCard(t){return `<button class="cc-task" data-task="${esc(t.id)}"><span class="cc-status ${esc(t.status)}"></span><div><b>${esc(t.title)}</b><small class="ltr">${esc(t.id)}</small></div><em>${esc(t.status)}</em></button>`}
  function artifactCard(a){return `<button class="cc-artifact" data-artifact="${esc(a.artifact_id||a.id)}"><span class="cc-file">▤</span><div><b>${esc(a.title||'بدون عنوان')}</b><small>${esc(a.source_type||'UNAVAILABLE')} · ${esc(a.created_at||'')}</small></div><em>${esc(a.health_state||'UNAVAILABLE')}</em></button>`}
  function eventRow(e){return `<div class="cc-event"><span class="cc-event-dot ${esc(e.status)}"></span><div><b>${esc(e.event_type)}</b><small>${esc(e.message)} · <span class="ltr">${esc((e.run_id||'').slice(0,18))}</span></small></div><time class="ltr">${esc(e.timestamp)}</time></div>`}
  function empty(t){return `<div class="cc-empty">${esc(t)}</div>`}
  function renderTasks(){$('#tasks-list').innerHTML=tasks.map(taskCard).join('')||empty('لا توجد مهام محفوظة.');}
  function renderInbox(){const q=($('#inbox-search')?.value||'').toLowerCase();$('#inbox-list').innerHTML=inbox.filter(a=>`${a.title} ${a.content} ${a.source_type}`.toLowerCase().includes(q)).map(artifactCard).join('')||empty('لا توجد نتائج مطابقة.');}
  function renderServices(){const sources=overview.sources||{};$('#services-list').innerHTML=Object.entries(sources).map(([name,s])=>`<article class="cc-service"><span class="cc-status ${s.health_state==='available'||s.health_state==='configured'?'completed':'unavailable'}"></span><h3>${esc(name)}</h3><b>${esc(s.health_state||'UNAVAILABLE')}</b><small>${esc(s.data_origin||'UNAVAILABLE')}<br>${esc(s.source_id||'UNAVAILABLE')}</small></article>`).join('')||empty('لا توجد خدمات موثقة.');}
  function renderKnowledge(){$('#knowledge-state').innerHTML='<span class="cc-knowledge-icon">⌘</span><h3>لا توجد ملاحظات بعد</h3><p>Vault: <span class="ltr">/root/obsidian-vault → /opt/data/obsidian</span><br>عدد الملاحظات: <b>0</b><br>Graph: <b>UNAVAILABLE</b></p><small>أضف أول ملاحظة إلى الـVault الفعلي لبدء بناء العلاقات.</small>';}
  async function load(){try{[overview]=await Promise.all([get('/api/system/overview')]);const ti=await get('/api/tasks');tasks=ti.tasks||[];for(const t of tasks){try{const d=await get('/api/tasks/'+t.id);t._events=d.events||[]}catch{t._events=[]}}const ii=await get('/api/inbox?limit=100');inbox=ii.items||[];$('#global-health').textContent=overview.health_state||'UNAVAILABLE';renderHome();renderTasks();renderInbox();renderServices();renderKnowledge();}catch(e){$('#global-health').textContent='UNAVAILABLE';$('#home-events').innerHTML=empty('تعذر تحميل المصادر: '+e.message)}}
  async function openTask(id){const d=await get('/api/tasks/'+id);activeTask=d;$('#detail-content').innerHTML=`<span class="eyebrow">TASK DETAILS</span><h2>${esc(d.task.title)}</h2><p>${esc(d.task.prompt)}</p><div class="cc-detail-meta"><b>status</b><span>${esc(d.task.status)}</span><b>task_id</b><span class="ltr">${esc(d.task.id)}</span><b>run_id</b><span class="ltr">${esc(d.run?.id||'UNAVAILABLE')}</span><b>conversation</b><span class="ltr">${esc(d.task.conversation_id)}</span></div><div class="cc-events">${(d.events||[]).map(eventRow).join('')}</div>${d.task.artifact_id?`<button class="cc-primary" data-artifact="${esc(d.task.artifact_id)}">فتح Artifact</button>`:''}${d.task.status==='failed'?`<button class="cc-secondary" data-retry="${esc(d.task.id)}">إعادة المحاولة</button>`:''}`;$('#detail-dialog').showModal()}
  async function openArtifact(id){const a=await get('/api/artifacts/'+id);$('#detail-content').innerHTML=`<span class="eyebrow">ARTIFACT</span><h2>${esc(a.title)}</h2><div class="cc-detail-meta"><b>task_id</b><span class="ltr">${esc(a.task_id)}</span><b>run_id</b><span class="ltr">${esc(a.run_id)}</span><b>mime</b><span>${esc(a.mime_type)}</span><b>source</b><span>${esc(a.source_type)} / ${esc(a.source_id)}</span><b>origin</b><span>${esc(a.data_origin)}</span><b>verified</b><span class="ltr">${esc(a.last_verified_at)}</span></div><pre class="cc-content">${esc(a.content)}</pre>`;$('#detail-dialog').showModal()}
  async function createTask(e){e.preventDefault();const p={title:$('#task-title').value,prompt:$('#task-prompt').value};const r=await fetch(api('/api/tasks'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error('تعذر إنشاء المهمة');$('#task-dialog').close();await load();show('tasks');}
  async function chat(){const input=$('#chat-input'),text=input.value.trim();if(!text)return;$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg user">${esc(text)}</div>`);input.value='';const r=await fetch(api('/api/chat'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const d=await r.json();$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg">${esc(d.reply||d.error||'UNAVAILABLE')}</div>`)}
  document.addEventListener('click',e=>{const t=e.target.closest('[data-task]');if(t)openTask(t.dataset.task);const a=e.target.closest('[data-artifact]');if(a)openArtifact(a.dataset.artifact);const r=e.target.closest('[data-retry]');if(r)fetch(api('/api/tasks/'+r.dataset.retry+'/retry'),{method:'POST'}).then(()=>{location.reload()})});$('#task-form').addEventListener('submit',e=>createTask(e).catch(err=>alert(err.message)));$('#chat-send').onclick=()=>chat();$('#inbox-search').oninput=renderInbox;nav();load();show(location.hash.slice(1)||'home');
})();
