(function(){
  const BASE=location.pathname.startsWith('/ui')?'/ui':'';const api=p=>BASE+p;const $=s=>document.querySelector(s);const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
  let tasks=[],inbox=[],overview={},knowledge={},activeTask=null;
  async function get(path){const r=await fetch(api(path),{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
  function nav(){document.querySelectorAll('[data-panel]').forEach(a=>a.onclick=e=>{e.preventDefault();show(a.dataset.panel)});document.querySelectorAll('[data-action="new-task"]').forEach(b=>b.onclick=()=>$('#task-dialog').showModal());}
  function show(name){document.querySelectorAll('[data-panel-content]').forEach(p=>p.classList.toggle('active',p.dataset.panelContent===name));const navName=['services','knowledge'].includes(name)?'more':name;document.querySelectorAll('.cc-nav').forEach(a=>a.classList.toggle('active',a.dataset.panel===navName));$('#page-title').textContent={home:'مركز القيادة',tasks:'المهام',inbox:'صندوق الوارد',chat:'المحادثة',more:'المزيد',knowledge:'المعرفة',services:'الخدمات'}[name]||'مركز القيادة';location.hash=name;if(name==='tasks')renderTasks();if(name==='inbox')renderInbox();if(name==='services')renderServices();if(name==='knowledge')renderKnowledge();}
  function metric(label,value,note){return `<div class="cc-metric"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></div>`}
  const statusLabels={received:'مستلمة',planning:'تخطيط',delegated:'مفوّضة',running:'قيد التنفيذ',completed:'مكتملة',failed:'فاشلة',cancelled:'ملغاة'};
  function renderHome(){const failed=tasks.filter(t=>t.status==='failed').length,running=tasks.filter(t=>['received','planning','delegated','running'].includes(t.status)).length,done=tasks.filter(t=>t.status==='completed').length;$('#home-metrics').innerHTML=metric('قيد التنفيذ',running,'من /api/tasks')+metric('فشل التنفيذ',failed,'بيانات حقيقية')+metric('مكتملة',done,'منذ بدء التخزين')+metric('النتائج',inbox.length,'من /api/inbox');$('#home-tasks').innerHTML=tasks.slice(0,3).map(taskCard).join('')||empty('لا توجد مهام بعد');$('#home-inbox').innerHTML=inbox.slice(0,3).map(artifactCard).join('')||empty('لا توجد نتائج بعد');const events=[];tasks.forEach(t=>{if(t._events)events.push(...t._events)});$('#home-events').innerHTML=events.sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,8).map(eventRow).join('')||empty('لا توجد أحداث بعد');}
  function taskCard(t){return `<button class="cc-task" data-task="${esc(t.id)}"><span class="cc-status ${esc(t.status)}"></span><div><b>${esc(t.title||'مهمة بلا عنوان')}</b><small class="ltr">${esc(t.id)}</small></div><em>${esc(statusLabels[t.status]||'UNAVAILABLE')}</em></button>`}
  function artifactCard(a){return `<button class="cc-artifact" data-artifact="${esc(a.artifact_id||a.id)}"><span class="cc-file">▤</span><div><b>${esc(a.title||'بدون عنوان')}</b><small>${esc(a.source_type||'UNAVAILABLE')} · ${esc(a.created_at||'')}</small></div><em>${esc(a.health_state||'UNAVAILABLE')}</em></button>`}
  function eventRow(e){const labels={'task.received':'تم استلام المهمة','task.planning':'جارٍ تجهيز المهمة','run.started':'بدأ التنفيذ','hermes.response':'وصل رد Hermes','artifact.created':'تم حفظ النتيجة','run.completed':'اكتمل التنفيذ','run.failed':'فشل التنفيذ'};return `<div class="cc-event"><span class="cc-event-dot ${esc(e.status)}"></span><div><b>${esc(labels[e.event_type]||e.event_type)}</b><small>${esc(e.message)} · <span class="ltr">${esc((e.run_id||'').slice(0,18))}</span></small></div><time class="ltr">${esc(e.timestamp)}</time></div>`}
  function empty(t){return `<div class="cc-empty">${esc(t)}</div>`}
  function renderTasks(){const q=($('#tasks-search')?.value||'').toLowerCase(),status=$('#tasks-status')?.value||'',sort=$('#tasks-sort')?.value||'updated';const rows=tasks.filter(t=>(!status||t.status===status)&&`${t.title} ${t.prompt} ${t.id}`.toLowerCase().includes(q)).sort((a,b)=>sort==='title'?String(a.title).localeCompare(String(b.title),'ar'):String(b[sort==='created'?'created_at':'updated_at']||b.created_at).localeCompare(String(a[sort==='created'?'created_at':'updated_at']||a.created_at)));$('#tasks-list').innerHTML=rows.map(taskCard).join('')||empty('لا توجد مهام مطابقة.');}
  function renderInbox(){const q=($('#inbox-search')?.value||'').toLowerCase();$('#inbox-list').innerHTML=inbox.filter(a=>`${a.title} ${a.content} ${a.source_type}`.toLowerCase().includes(q)).map(artifactCard).join('')||empty('لا توجد نتائج مطابقة.');}
  function renderServices(){const sources=overview.sources||{};$('#services-list').innerHTML=Object.entries(sources).map(([name,s])=>`<article class="cc-service"><span class="cc-status ${s.health_state==='available'||s.health_state==='configured'?'completed':'unavailable'}"></span><h3>${esc(name)}</h3><b>${esc(s.health_state||'UNAVAILABLE')}</b><small>${esc(s.data_origin||'UNAVAILABLE')}<br>${esc(s.source_id||'UNAVAILABLE')}</small></article>`).join('')||empty('لا توجد خدمات موثقة.');}
  function renderKnowledge(){const s=overview.sources?.knowledge_graph||{};const status=knowledge.status||s.health_state||'UNAVAILABLE';const count=Array.isArray(knowledge.nodes)?knowledge.nodes.length:0;$('#knowledge-state').innerHTML=`<span class="cc-knowledge-icon">⌘</span><h3>${status==='UNAVAILABLE'?'لا توجد ملاحظات متاحة بعد':'المعرفة المترابطة'}</h3><p>المصدر: <span class="ltr">${esc(knowledge.source_id||s.source_id||'UNAVAILABLE')}</span><br>عدد العقد: <b>${esc(count)}</b><br>Graph: <b>${esc(status)}</b></p><small>${esc(knowledge.reason||'تُعرض العلاقات من المصدر الفعلي فقط، دون بيانات تجريبية.')}</small>`;}
  async function load(){try{[overview,knowledge]=await Promise.all([get('/api/system/overview'),get('/api/knowledge/graph')]);const ti=await get('/api/tasks');tasks=ti.tasks||[];for(const t of tasks){try{const d=await get('/api/tasks/'+t.id);t._events=d.events||[]}catch{t._events=[]}}const ii=await get('/api/inbox?limit=100');inbox=ii.items||[];$('#global-health').textContent=overview.health_state||'UNAVAILABLE';renderHome();renderTasks();renderInbox();renderServices();renderKnowledge();}catch(e){$('#global-health').textContent='UNAVAILABLE';$('#home-events').innerHTML=empty('تعذر تحميل المصادر: '+e.message)}}
  async function openTask(id){const d=await get('/api/tasks/'+id);activeTask=d;$('#detail-content').innerHTML=`<span class="eyebrow">TASK DETAILS</span><h2>${esc(d.task.title)}</h2><p>${esc(d.task.prompt)}</p><div class="cc-detail-meta"><b>status</b><span>${esc(d.task.status)}</span><b>task_id</b><span class="ltr">${esc(d.task.id)}</span><b>run_id</b><span class="ltr">${esc(d.run?.id||'UNAVAILABLE')}</span><b>conversation</b><span class="ltr">${esc(d.task.conversation_id)}</span></div><div class="cc-events">${(d.events||[]).map(eventRow).join('')}</div>${d.task.artifact_id?`<button class="cc-primary" data-artifact="${esc(d.task.artifact_id)}">فتح Artifact</button>`:''}${d.task.status==='failed'?`<button class="cc-secondary" data-retry="${esc(d.task.id)}">إعادة المحاولة</button>`:''}`;$('#detail-dialog').showModal()}
  async function openArtifact(id){const a=await get('/api/artifacts/'+id);$('#detail-content').innerHTML=`<span class="eyebrow">ARTIFACT</span><h2>${esc(a.title)}</h2><div class="cc-detail-meta"><b>task_id</b><span class="ltr">${esc(a.task_id)}</span><b>run_id</b><span class="ltr">${esc(a.run_id)}</span><b>mime</b><span>${esc(a.mime_type)}</span><b>source</b><span>${esc(a.source_type)} / ${esc(a.source_id)}</span><b>origin</b><span>${esc(a.data_origin)}</span><b>verified</b><span class="ltr">${esc(a.last_verified_at)}</span></div><pre class="cc-content">${esc(a.content)}</pre>`;$('#detail-dialog').showModal()}
  async function createTask(e){e.preventDefault();const p={title:$('#task-title').value,prompt:$('#task-prompt').value};const r=await fetch(api('/api/tasks'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});if(!r.ok)throw Error('تعذر إنشاء المهمة');$('#task-dialog').close();await load();show('tasks');}
  async function chat(){const input=$('#chat-input'),text=input.value.trim();if(!text)return;$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg user">${esc(text)}</div>`);input.value='';const r=await fetch(api('/api/chat'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:text})});const d=await r.json();$('#chat-thread').insertAdjacentHTML('beforeend',`<div class="cc-chat-msg">${esc(d.reply||d.error||'UNAVAILABLE')}</div>`)}
  document.addEventListener('click',e=>{const t=e.target.closest('[data-task]');if(t)openTask(t.dataset.task);const a=e.target.closest('[data-artifact]');if(a)openArtifact(a.dataset.artifact);const r=e.target.closest('[data-retry]');if(r)fetch(api('/api/tasks/'+r.dataset.retry+'/retry'),{method:'POST'}).then(()=>{location.reload()});const refresh=e.target.closest('[data-action="refresh"]');if(refresh)load();});$('#task-form').addEventListener('submit',e=>createTask(e).catch(err=>alert(err.message)));$('#chat-send').onclick=()=>chat();$('#inbox-search').oninput=renderInbox;$('#tasks-search').oninput=renderTasks;$('#tasks-status').onchange=renderTasks;$('#tasks-sort').onchange=renderTasks;nav();load();show(location.hash.slice(1)||'home');
})();
